CREATE TABLE PRODUCT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)  NOT NULL,
    description VARCHAR(2000) NULL,
    price DECIMAL(7, 2) NOT NULL,
    category_id BIGINT NOT NULL
);

CREATE TABLE CATEGORY (
    category_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

ALTER TABLE PRODUCT
    ADD FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);
